#Requires -Version 7
<#
PinnedLauncher P0.2 check (throwaway): shell:AppsFolder enumeration
perf/ordering for the installed-apps picker (management-window §8 open
question 1). Fully programmatic, no gestures.

Measures, via the Shell COM automation objects (slower than the product's
native IShellFolder/IEnumIDList — so every timing here is an UPPER bound):
  - full enumeration + materialization time, two passes (warm/warm);
  - per-item Name and Path (= parse name = AUMID) access time;
  - returned ordering vs a locale-aware name sort;
  - display-name duplicates;
  - parse-name shape distribution (packaged '!' AUMIDs, explicit dotted
    AUMIDs, auto-generated ones, raw file paths) — the picker needs the
    AUMID for the S-4 deep link and to classify the target kind;
  - a sampled cross-check that ExtendedProperty('System.AppUserModel.ID')
    agrees with Path.

Writes results\appsfolder-enum-<timestamp>.json for transcription into
docs/spikes/appsfolder-enum.md. Re-run after a reboot for a cold-cache
datum (pass -Label cold).
#>
[CmdletBinding()]
param(
    [string]$Label = 'warm'
)
$ErrorActionPreference = 'Stop'

$cv = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
$build = "$($cv.CurrentBuildNumber).$($cv.UBR)"
"environment: $($cv.ProductName) $($cv.DisplayVersion) build $build"
"label: $Label"

$shell = New-Object -ComObject Shell.Application

function Measure-Pass {
    $folder = $shell.Namespace('shell:AppsFolder')
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $items = @($folder.Items())
    $tEnum = $sw.Elapsed.TotalMilliseconds

    $sw.Restart()
    $names = foreach ($i in $items) { $i.Name }
    $tNames = $sw.Elapsed.TotalMilliseconds

    $sw.Restart()
    $paths = foreach ($i in $items) { $i.Path }
    $tPaths = $sw.Elapsed.TotalMilliseconds

    [ordered]@{
        count   = $items.Count
        enumMs  = [math]::Round($tEnum, 1)
        namesMs = [math]::Round($tNames, 1)
        pathsMs = [math]::Round($tPaths, 1)
        totalMs = [math]::Round($tEnum + $tNames + $tPaths, 1)
        items   = $items; names = $names; paths = $paths
    }
}

$pass1 = Measure-Pass
$pass2 = Measure-Pass
"pass 1: {0} items - enum {1} ms, names {2} ms, paths {3} ms, total {4} ms" -f $pass1.count, $pass1.enumMs, $pass1.namesMs, $pass1.pathsMs, $pass1.totalMs
"pass 2: {0} items - enum {1} ms, names {2} ms, paths {3} ms, total {4} ms" -f $pass2.count, $pass2.enumMs, $pass2.namesMs, $pass2.pathsMs, $pass2.totalMs

# Ordering: is the returned sequence the locale-aware sort of the names?
$names = [string[]]$pass2.names
$sorted = [string[]]($names | Sort-Object -Culture (Get-Culture).Name)
$sortedCI = [string[]]($names | Sort-Object)   # default: current culture, case-insensitive
$isSorted = $true
for ($i = 0; $i -lt $names.Count; $i++) {
    if ($names[$i] -cne $sorted[$i] -and $names[$i] -cne $sortedCI[$i]) { $isSorted = $false; break }
}
$firstDivergence = $isSorted ? $null : ("index {0}: returned '{1}' vs sorted '{2}'" -f $i, $names[$i], $sorted[$i])
"returned order is locale-aware name sort: $isSorted" + ($firstDivergence ? " (first divergence: $firstDivergence)" : '')
"first 10 in returned order: " + (($names | Select-Object -First 10) -join ' | ')

# Duplicate display names (the picker must disambiguate, e.g. by AUMID/publisher).
$dupes = @($pass2.names | Group-Object | Where-Object Count -gt 1 | Sort-Object Count -Descending)
"duplicate display names: $($dupes.Count)"
foreach ($d in ($dupes | Select-Object -First 8)) { "  '{0}' x{1}" -f $d.Name, $d.Count }

# Parse-name (AUMID) shape distribution.
$shapes = [ordered]@{ packagedBang = 0; autoGenerated = 0; filesystemPath = 0; explicitDotted = 0; other = 0 }
$shapeSamples = [ordered]@{ packagedBang = $null; autoGenerated = $null; filesystemPath = $null; explicitDotted = $null; other = $null }
foreach ($p in $pass2.paths) {
    $shape = if ($p -like '*!*') { 'packagedBang' }
             elseif ($p -like 'Microsoft.AutoGenerated.*') { 'autoGenerated' }
             elseif ($p -match '^[A-Za-z]:\\|^\\\\') { 'filesystemPath' }
             elseif ($p -like '*.*') { 'explicitDotted' }
             else { 'other' }
    $shapes[$shape]++
    if (-not $shapeSamples[$shape]) { $shapeSamples[$shape] = $p }
}
"parse-name shapes:"
foreach ($k in $shapes.Keys) { "  {0}: {1}{2}" -f $k, $shapes[$k], ($shapeSamples[$k] ? " (e.g. $($shapeSamples[$k]))" : '') }

# Sampled cross-check: ExtendedProperty AUMID vs Path, and its per-item cost.
$sampleN = [math]::Min(25, $pass2.count)
$sw = [System.Diagnostics.Stopwatch]::StartNew()
$mismatches = 0
for ($i = 0; $i -lt $sampleN; $i++) {
    $item = $pass2.items[$i * [math]::Floor($pass2.count / $sampleN)]
    $ep = $item.ExtendedProperty('System.AppUserModel.ID')
    if ($ep -and ($ep -cne $item.Path)) { $mismatches++ }
}
$tEp = $sw.Elapsed.TotalMilliseconds
"ExtendedProperty(System.AppUserModel.ID) vs Path on $sampleN sampled items: $mismatches mismatches, {0} ms total ({1} ms/item)" -f [math]::Round($tEp,1), [math]::Round($tEp/$sampleN,2)

# Leftover check: no PinnedLauncher.* entries should linger post-S-8.
$leftovers = @($pass2.paths | Where-Object { $_ -like 'PinnedLauncher.*' })
"PinnedLauncher.* entries present: $($leftovers.Count)" + ($leftovers ? " ($($leftovers -join ', '))" : '')

$resultsDir = Join-Path $PSScriptRoot 'results'
New-Item -ItemType Directory -Force $resultsDir | Out-Null
$resultsPath = Join-Path $resultsDir ("appsfolder-enum-{0}-{1:yyyyMMdd-HHmmss}.json" -f $Label, (Get-Date))
[ordered]@{
    run = 'appsfolder-enum'; label = $Label; at = (Get-Date).ToString('o'); build = $build
    pass1 = [ordered]@{ count = $pass1.count; enumMs = $pass1.enumMs; namesMs = $pass1.namesMs; pathsMs = $pass1.pathsMs; totalMs = $pass1.totalMs }
    pass2 = [ordered]@{ count = $pass2.count; enumMs = $pass2.enumMs; namesMs = $pass2.namesMs; pathsMs = $pass2.pathsMs; totalMs = $pass2.totalMs }
    orderedByName = $isSorted; firstDivergence = $firstDivergence
    first10 = @($names | Select-Object -First 10)
    duplicateNames = @($dupes | ForEach-Object { [ordered]@{ name = $_.Name; count = $_.Count } })
    shapes = $shapes; shapeSamples = $shapeSamples
    extendedPropertySample = [ordered]@{ n = $sampleN; mismatches = $mismatches; totalMs = [math]::Round($tEp,1) }
    pinnedLauncherLeftovers = $leftovers
} | ConvertTo-Json -Depth 6 | Set-Content $resultsPath -Encoding utf8
"results written to: $resultsPath"
